name: Generate AltureTV HLS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download video from Dropbox
        run: |
          mkdir input
          wget -O input/video.avi "https://dl.dropboxusercontent.com/scl/fi/mec5mt2707xz0c61fms8j/big_buck_bunny_720p_surround.avi?rlkey=b6jkt7rsw2nue4jummwoss4ef&st=t4s3wzwm"

      - name: Generate HLS
        run: |
          mkdir -p output/bbb
          ffmpeg -stream_loop -1 -i input/video.avi \
            -vf scale=1280:-1 \
            -c:v libx264 -preset veryfast -crf 28 \
            -c:a aac -b:a 96k \
            -f hls -hls_time 6 -hls_list_size 0 \
            -hls_segment_filename "output/bbb/segment_%03d.ts" \
            output/bbb/stream.m3u8

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
